apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: default
  labels:
    app.kubernetes.io/name: express-app
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        # This image tag will be updated automatically by GitHub Actions CI
        image: docker.io/raghu2603/express-app:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        # Resource requests & limits prevent container resource starvation
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        # Kubernetes Liveness Probe checks if application crashed
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        # Readiness Probe checks if pod is ready to accept traffic
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5